### ISSUE TITLE
Setting Environment Variables on Windows

### ISSUE THREAD

**Issue by dadede** [peeter123/digikey-api#1]
I set up the variables are directed but I get the error: 'ValueError: CLIENT ID and SECRET must be set. Set 'DIGIKEY_CLIENT_ID' and 'DIGIKEY_CLIENT_SECRET' as an environment variable, or pass your keys directly to the client.'

How do I call the client and set it up directly? Or better still how can I properly set up the variables and call os.environ? Note: I didn't work so I used os.geten, didn't work still.

Thanks for the help!

**Comment by peeter123** [comment]
Should work like described in the [Readme](https://github.com/peeter123/digikey-api#use). Did you import the `os` module? I ran the the code shown in the readme and it works fine.

**Comment by dadede** [comment]
Oh yes I did. But it doesn’t seem to work on windows. Do you know how to
pass the api variables directly instead?

**Comment by peeter123** [comment]
I am also on windows, if you want to pass directly see the [api](https://github.com/peeter123/digikey-api/blob/master/digikey/api.py#L25) code, copy that and pass the required stuff to DigikeyClient().

It is strange though that os.environ does not work, you should investigate that, as I am also testing on Windows.

**Comment by dadede** [comment]
client = DigikeyClient(client-id,client-secret,location)

Where I substituted with the actual api variables I have.

I have that replacing  os.environ, still doesn’t work. But am I doing that
right? I’m new to python, thanks for your help!

**Comment by dadede** [comment]
I've made some progress. Figured out why os.environ was not working. Had to import os.
Now I'm getting this error:
os.environ['DIGIKEY_CLIENT_ID'] = client_id
NameError: name 'client_id' is not defined.

Any clue that can help solve this? Thank you!

**Comment by peeter123** [comment]
Well you need to replace client_id with the actual client_id. Please read the README.md
