### ISSUE TITLE
Possibility to get the remaining number of requests in a variable

### ISSUE THREAD

**Issue by clementspeter** [peeter123/digikey-api#10]
Dear All,
Is there a possibility to get the remaining number of requests somehow by calling a function ?
I correctly get it printed, but ideally I would like to store it in a variable.
Thank you very much,
Best,
Peter

**Comment by Funkenjaeger** [comment]
I experimented with this in a branch on my fork:
https://github.com/Funkenjaeger/digikey-api/tree/rate_limit_info

I have it working (just for `manufacturer_product_details()` as a starting point), but I don't feel like my initial implementation is very elegant.  
The rate limit information is returned in the header that comes alongside the object containing the actual results of the request.  The trouble is that all the various functions defined in `digikey.v3.api` (such as `manufacturer_product_details()` each create a local instance of the DigikeyApiWrapper class to perform the request, but only the object representing the actual results of the request (e.g. a ProductDetails object) is returned.  Those classes are auto-generated by swagger, so I don't want to go messing with them to embed the rate limit information.    

One option could be to change the functions in digikey.v3.api to return a separate object containing the rate limit info alongside the actual response object (e.g. as a tuple), but that function signature change would be disruptive to any existing code using the library.

What I elected to do instead was to create a global `rate_limit_info` in digikey.v3.api which gets updated during each API request.  It's set up as a dict with two elements `'product_information'` and `'order_support'` to reflect the fact that there are independent rate limits for different digikey APIs.   I don't really love using a global, but it does avoid changing the signature of the top-level functions so shouldn't break any existing code using the library.

I'm open to comments or suggestions on a better way to approach it.

**Comment by clementspeter** [comment]
@Funkenjaeger Yes, I came to the same conclusion while I was looking at the code and unfortunately I do not see either a way to do it differently without causing a problem to existing code... Looking forward to what the others might have in mind...

**Comment by peeter123** [comment]
I though a bit about it and came to the same conclusion as you did, it is difficult to implement these changes without breaking previous code. 

Then I thought we could leverage Python's pass by reference + mutable types to pass an optional api_limits empty dict kwarg and append to the dict if the api_limits kwarg exists. This seems to work great. See [my api_limits test branch](/peeter123/digikey_api/tree/api_limits).

Could you please test this? Use it something like this:
```python
api_limit = {}
search_request = KeywordSearchRequest(keywords='CRCW080510K0FKEA', record_count=10)
result = digikey.keyword_search(body=search_request, api_limits=api_limit)
```

What do you guys think about this solution?

**Comment by Funkenjaeger** [comment]
@peeter123 Your solution seems to work great for me as well - and it seems like a very 'clean' solution.  I like it!

**Comment by clementspeter** [comment]
@peeter123 Definitely a good possibility. 
Could you please also push to have the digikey-api package updated ? (I use the "import digikey-api" directly from python) - the version nb should also be incremented.
Thank you for the effort

**Comment by peeter123** [comment]
@clementspeter Need to do a bit more testing before releasing to PyPI, in the meantime you can use `pip install git+https://github.com/peeter123/digikey-api.git`

**Comment by clementspeter** [comment]
@peeter123 super, thanks for the extra effort!

**Comment by eeintech** [comment]
@peeter123 Was this released to PyPI?

**Comment by peeter123** [comment]
@eeintech I have pushed 0.5.0 with the above fix to PyPI!
