### ISSUE TITLE
Choosing currency and country

### ISSUE THREAD

**Issue by Phil9347** [peeter123/digikey-api#12]
Hello my dudes,

I was wondering how to change the currency and the country when doing a ProductDetails call. I found on the DK API website that you can pass the X-DIGIKEY-Locale-Site header and the X-DIGIKEY-Locale-Currency, but I'm not sure how to implement it in the code, since I'm not that great in Python. 

Can you help me with that?

**Comment by Funkenjaeger** [comment]
Those extra optional parameters can be passed as keyword arguments.  For example, this yielded a response in German, with pricing in Euros:
`part = digikey.product_details('RE0402BRE07100RL', x_digikey_locale_site='DE', x_digikey_locale_language='de', x_digikey_locale_currency='EUR')`

**Comment by Phil9347** [comment]
Thank you!
