### ISSUE TITLE
Missing parameters in GRM1885C1H560FA01J

### ISSUE THREAD

**Issue by clementspeter** [peeter123/digikey-api#13]
Dear All,

I came accross an interesting component : the GRM1885C1H560FA01J on digi-key (490-11467-1-ND)
- the script output is missing the digi-reel part number (490-11467-6-ND)
- it it set as "discontinued at digikey", but nothing is indicated on the website (not a big deal, but still interesting)  ;)
could you please have look why the reel information is not given?
Thank you!

**Comment by Funkenjaeger** [comment]
This module is just wrapping calls to Digikey's public REST API - if the Digikey API returns suspicious or erroneous results, there's not a lot that this tool can do about it.

As far as the results for this specific part, note that in the right-hand column (under "Add to Cart") the first table only says "Tape & Reel (TR)" and only lists qty 10000, whereas for other parts it normally says "Cut Tape (CT) & Digi-Reel®" and lists multiple quantity options.  This suggests that Digikey is not currently offering this part in Digi-Reel packaging, even though they do have a part number for it.
As for why the part is marked as discontinued, who knows - you'd have to ask Digikey.

**Comment by eeintech** [comment]
@clementspeter Wanna close this issue if you have no more question?
