### ISSUE TITLE
digikey.status_saleorder_id() returns None

### ISSUE THREAD

**Issue by laf0rge** [peeter123/digikey-api#18]
When using the sandbox v3 OrderDetailsApi, I'm getting a valid response to 
`digikey.salesorder_history(start_date='2000-01-01', end_date='2021-12-31')`:

```
[{'customer_id': 8675309,
 'date_entered': '2000-01-01T00:00:00.0000000-06:00',
 'purchase_order': 'TEST',
 'salesorder_id': 58223023}, {'customer_id': 8675309,
 'date_entered': '2021-12-31T00:00:00.0000000-06:00',
 'purchase_order': 'PO123',
 'salesorder_id': 58150868}]
```

If I then use one of the salesorder_id to query the details of that order using `digikey.status_salesorder_id(sales_order_id=58223023)`, I only get None as a result.

Did anyone manage to make this work? Is there any example about listing the positions of a sales order?

Thanks!

**Comment by laf0rge** [comment]
In fact, it doesn't even seem to make the API request.  For the first call (salesorder_history) I get
```
2021-06-09 17:01:28,964 - digikey.oauth.oauth2 -    DEBUG: Using API V3
DEBUG:digikey.oauth.oauth2:Using API V3
2021-06-09 17:01:28,964 -       digikey.v3.api -     INFO: Searching for orders in date range 2000-01-01 to 2021-12-31
INFO:digikey.v3.api:Searching for orders in date range 2000-01-01 to 2021-12-31
2021-06-09 17:01:28,964 -       digikey.v3.api -    DEBUG: CALL wrapped -> OrderDetailsApi.order_history_with_http_info
DEBUG:digikey.v3.api:CALL wrapped -> OrderDetailsApi.order_history_with_http_info
2021-06-09 17:01:29,639 -       digikey.v3.api -    DEBUG: Requests remaining: [994/1000]
DEBUG:digikey.v3.api:Requests remaining: [994/1000]
[{'customer_id': 8675309,
 'date_entered': '2000-01-01T00:00:00.0000000-06:00',
 'purchase_order': 'TEST',
 'salesorder_id': 58223023}, {'customer_id': 8675309,
 'date_entered': '2021-12-31T00:00:00.0000000-06:00',
 'purchase_order': 'PO123',
 'salesorder_id': 58150868}]
```

and for the second call (status_salesorder_id) I only get
```
2021-06-09 17:01:29,643 - digikey.oauth.oauth2 -    DEBUG: Using API V3
DEBUG:digikey.oauth.oauth2:Using API V3
```

**Comment by laf0rge** [comment]
I figured out what my error was: I should have passed the sales order ID (58223023) as a positional argument and not as a keyword argument.

So `digikey.status_salesorder_id(58223023)` works but `digikey.status_salesorder_id(sales_order_id=58223023)` neither complains about a missing positional argument, nor does it complain an unexpected/unsupported kwarg was given.  It simply returns None.

**Comment by eeintech** [comment]
@laf0rge If possible, close the issue if resolved?

**Comment by peeter123** [comment]
@laf0rge The lib just passes on the args and kwargs to the underlying api functions so you need to adhere to their conventions.
