### ISSUE TITLE
Trouble after DigiKey Update

### ISSUE THREAD

**Issue by emsnano** [peeter123/digikey-api#28]
Hello,
After update the DigiKey page no longer sees "ExcludeMarketPlaceProducts" and "RequestedQuantity" values in our requests in KeywordSearchRequest. Can you check it please and tell what we need to change to solve this problem? 

Karavaev Konstantin

**Comment by peeter123** [comment]
Hi I don't exactly know what you mean, this package follows the API specification provided by Digi-key. If something is missing they have probably removed it. 

Could you provide an example of what you are trying to achieve?

**Comment by emsnano** [comment]
Hi,
Our request looks like that: 
search_request = KeywordSearchRequest(keywords=Parametry_szukanego_podzespolu, record_count=49, exclude_market_place_products = True, sort = {"SortOption" : "SortByUnitPrice", "Direction" : "Ascending"} , requested_quantity = int(ilosc4))   
result_mokryj = digikey.keyword_search(body=search_request, includes = "Products(DigiKeyPartNumber,ManufacturerPartNumber,ProductDescription,QuantityAvailable,MinimumOrderQuantity,StandardPricing)", x_digikey_locale_currency = 'PLN', x_digikey_locale_site = 'PL', x_digikey_locale_language = 'en' ) 

The algorithm:
1.	Change string “Parametry_szukanego_podzespolu” on value like “4,7k 0805 1%” and “int(ilosc4)” on int value ( for  example 45 )
2.	 Send request on DigiKey with keyword, record_count, exclude_market_place_products, sort_parametrs and requested_quantity
3.	Get answer for Poland
4.	Choose from 49 parts the cheapiest one for our requested quantity (if we need 100 resistors we don`t want to buy parts with minimum quantity 10000 pcs) and which is able on stock now.
5.	…
6.	…

After DigiKey update our algorithm give us back results for the keyword, record count and sort options but it does not see exclude_market_place_products and our requested quantity. It give us 10000+ minimum quantity and non-stock parts.

**Comment by emsnano** [comment]
Update!
Problem resolved. Developers had a little issue with sorting parameters and told me that they would fix it. Sorry for disturbing
