### ISSUE TITLE
Change Currency Setup

### ISSUE THREAD

**Issue by krlbckr** [peeter123/digikey-api#41]
Is it possible to change the currency setup for the requests to EUR?

**Comment by peeter123** [comment]
This is possible, just set the x_digikey_locale_currency kwarg:

:param str x_digikey_locale_currency: Three letter code for Currency to return part pricing for. Currency must be supported by the selected site. Acceptable values include: USD, CAD, JPY, GBP, EUR, HKD, SGD, TWD, KRW, AUD, NZD, INR, DKK, NOK, SEK, ILS, CNY, PLN, CHF, CZK, HUF, RON, ZAR, MYR, THB, PHP.

As shown in the part_search_api.py file.

```python
api_limit = {}
search_request = KeywordSearchRequest(keywords='CRCW080510K0FKEA', record_count=10)
result = digikey.keyword_search(body=search_request, api_limits=api_limit, x_digikey_locale_currency='EUR')
pprint(result)
```
