### ISSUE TITLE
Remove distutils

### ISSUE THREAD

**Issue by xlxs4** [peeter123/digikey-api#48]
`distutils` is deprecated and removed since python 3.12. This means that the package can not be used as a dependency in packages that aim to be compatible with python >3.11.
To replace distutils, you can take a look at this [SO thread](https://stackoverflow.com/questions/69858963/how-can-one-fully-replace-distutils-which-is-deprecated-in-3-10) and the referenced [Migration Advice](https://peps.python.org/pep-0632/#migration-advice). The only use of distutils in your package is in https://github.com/peeter123/digikey-api/blob/bf24772fa55d6ed457bc5c862a9165985cff10a8/digikey/v3/api.py#L3. Specifically, you're using `strtobool`. As per the migration advice, `strtobool` doesn't come with a drop-in replacement and you'll have to reimplement it yourself accordingly. [This PR](https://github.com/drgarcia1986/simple-settings/pull/281/files) from a different package (I'm sure there's more, that was the first result in my search) does exactly that, so you can get inspired or copy the definition. The specification for `strtobool` can be found [here](https://docs.python.org/3.9/distutils/apiref.html#distutils.util.strtobool).

**Comment by mofosyne** [comment]
Hope this gets fixed. In the meantime for product search, I've figured out the minimum needed to access it in https://gist.github.com/mofosyne/e15bb122024ff97ecc707dac68ab92b5 (In case anyone else is stuck and just need basic access to the apis)

**Comment by peeter123** [comment]
This has been released in version 1.1.0.
