### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by JaredTCan** [peeter123/digikey-api#6]
Running the v3 branch, the "use" example in the readme results in 
{"ErrorResponseVersion":"3.0.0.0","StatusCode": 401,"ErrorMessage":"Invalid clientId","ErrorDetails":"clientId invalid for requested resource","RequestId":"fae07ab5-88cf-4582-e7df-94d89fb8f9b4","ValidationErrors":[]}

On the page where I'd expect to see a user login. I've checked and double checked that my clientid is valid

**Comment by peeter123** [comment]
I think you created a sandbox application, you need to create a production application for it to work. 

You can however now use sandbox API as well (see updated branch)

**Comment by howardwang0620** [comment]
I created a production application and using the example, I've received an error with authentication:
digikey.oauth.oauth2 - WARNING: Token storage does not exist or malformed, creating new.
The oauth2 authentication in the browser is giving me error "400 - Unknown or invalid client_id".
Everything seems to be in order with client id and client secret, not sure why I'm getting this error

**Comment by Amdixer** [comment]
> I created a production application and using the example, I've received an error with authentication:
> digikey.oauth.oauth2 - WARNING: Token storage does not exist or malformed, creating new.
> 
> The oauth2 authentication in the browser is giving me error "400 - Unknown or invalid client_id".
> 
> Everything seems to be in order with client id and client secret, not sure why I'm getting this error

Having this problem as well.

**Comment by peeter123** [comment]
I have pushed improved oauth debug logging to digikey-api-v3, please make sure you check in the logging you have the correct urls / id / secret.

**Comment by peeter123** [comment]
Closed due to inactivity
