### ISSUE TITLE
About the log-in requirement

### ISSUE THREAD

**Issue by RainZhangZZFLS** [peeter123/digikey-api#7]
Hello Peter,

I have a small question. Every time when I switch to a new computer with digikey-api, I need to log in digikey's website through the browser. I wondered if I can do it via scripts since I want this code to work on the servers.

Thanks for taking your time!
Best,
Runze

**Comment by eeintech** [comment]
@peeter123 I actually have the same question, how can one automate the creation of API token without the need for manual steps through the browser?

**Comment by peeter123** [comment]
I don't think we can automate it as oauth2 by definition requires users to sign in and allow access. As a workaround you could maybe use a terminal browser like lynx or w3m to keep it in the command line?

**Comment by RainZhangZZFLS** [comment]
An update about my issue:
Recently when I tried to run this code on my Mac computer, I found there is a new file 'C/' and there is a 'token_storage.json' inside it. With this json file I copied my codes to a new Mac computer, I can circumvent the browser. I am not for sure if this is a general case, if you are interested, you can have a try. 
<img width="143" alt="Snipaste_2020-11-09_15-08-52" src="https://user-images.githubusercontent.com/36270330/98510327-dabd9700-229d-11eb-9a57-543bf717132b.png">
<img width="290" alt="Snipaste_2020-11-09_15-09-36" src="https://user-images.githubusercontent.com/36270330/98510332-dc875a80-229d-11eb-8813-6f2d479d404a.png">

**Comment by eeintech** [comment]
@RainZhangZZFLS Did you solve your issue?

**Comment by RainZhangZZFLS** [comment]
> @RainZhangZZFLS Did you solve your issue?

No, but I just used the authentication JSON file to circumvent this issue. I updated in several days using a GUI and then scp it to the server-side.

**Comment by eeintech** [comment]
@RainZhangZZFLS Ok nice this is what I have been doing too. Maybe close this issue now?
